RDKCOM-4143: REFPLTB-2449 : DHCP manager compilation issues in kirkstone
Reason for change :
rdkb/components/opensource/ccsp/DhcpManager/source/DHCPClientUtils/DHCPv4Client/service_dhcpv4_client.c:230:67: error: format '%x' expects argument of type 'unsigned int', but argument 5 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|   230 |             rc = sprintf_s(options + opt_len, (length - opt_len), "%02x", strlen(subopt_value));
|       |                                                                   ^~~~~~  ~~~~~~~~~~~~~~~~~~~~
|       |
changed the int format to %zu,due to strlen()
Test Procedure: 1.Verified that it is not affecting dunfell build.
                2.do_compile issues should not be observed in dhcp-manager
Risks: Low
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>

Reason for change: REFPLTB-2449 : DHCP manager compilation issues in kirkstone

(cherry picked from commit a8e48310cab2d04af7361018584746448e89432e)
Change-Id: I5807424894dae69a514625b813faabef52b24f75