RDKCOM-3622: RDKBCMF-303 DhcpManager build failure in RPi4 Broadband 64bit
Reason for change:
DhcpManager build failure in RPi4 Broadband 64bit
| DhcpManager/source/DHCPServerUtils/service_dhcp_server.c:233:58: error: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   233 |             fprintf(stdout, DNSMASQ getRFC_Value %s %s %d\n,status,l_DnsStrictOrderStatus,sizeof(l_DnsStrictOrderStatus));
|       |                                                         ~^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                          |                                  |
|       |                                                          int                                long unsigned int
|       |                                                         %ld
| DhcpManager/source/DHCPServerUtils/service_dhcp_server.c:237:78: error: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   237 |             fprintf(stdout, FAILURE: DNSMASQ getRFC_Value syscfg_get %s %s %d\n,status,l_DnsStrictOrderStatus,sizeof(l_DnsStrictOrderStatus));
|       |                                                                             ~^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                              |                                  |
|       |                                                                              int                                long unsigned int
|       |                                                                             %ld

| DhcpManager/source/service_udhcpc/service_udhcpc.c:709:32: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
|   709 |               ipv4_dns_match = (char *)(strstr(buffer,dns_server_list[i].data) || strstr(buffer,nameserver 127.0.0.1));
|       |                                ^

| DhcpManager/source/TR-181/middle_layer_src/cosa_dhcpv4_dml.c:3948:35: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|  3948 |                 CcspTraceWarning((pStaticClients->entries_count is %u\n, pStaticClients->entries_count));
|       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                                          |
|       |                                                                                          size_t {aka long unsigned int}

| DhcpManager/source/TR-181/middle_layer_src/cosa_dhcpv4_dml.c:4038:35: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|  4038 |                 CcspTraceWarning((pLanInfo->entries_count is %u\n, pLanInfo->entries_count));
|       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                              |
|       |                                                                              size_t {aka long unsigned int}

| DhcpManager/source/TR-181/middle_layer_src/cosa_dhcpv4_dml.c:6103:31: error: format '%d' expects argument of type 'int', but argument 10 has type 'long unsigned int' [-Werror=format=]
|  6103 |             CcspTraceWarning((%s: pPool->Cfg.DomainName: %s  0x%1x 0x%1x 0x%1x 0x%1x, sizeof: %d\n,
|       |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ......
|  6106 |                               (signed) (pPool->Cfg.DomainName[3]), sizeof(pPool->Cfg.DomainName)));
|       |                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                    |
|       |                                                                    long unsigned int

|  7974 |             CcspTraceWarning(('%s' value should be less than (%d) charecters\n, ParamName, ( sizeof(pDhcpStaticAddress->DeviceName) - 1 )));
|       |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                                              |
|       |                                                                                              long unsigned int

|  7993 |             CcspTraceWarning(('%s' value should be less than (%d) charecters\n, ParamName, ( sizeof(pDhcpStaticAddress->Comment) - 1 )));
|       |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                                              |
|       |                                                                                              long unsigned int

Test Procedure: Sanity.
Risks: None.

Signed-off-by: Simon Chung <simon_chung@comcast.com>
(cherry picked from commit 9f98c9ec966e1f013c2d126bad29f63c2c6f61ec)
Change-Id: I6bfe01ca0293dfba52977b3259af0ce78f8eae80