RDKCOM-3347: RDKBDEV-1273: cleanup + generalise AnscValidStringCheck()
Reason for change: Added to resolve compilation error differ in signedness .
cosa_dhcpv4_dml.c:7924:33: error: pointer targets in passing argument 1 of
'AnscValidStringCheck' differ in signedness [-Werror=pointer-sign]
Test Procedure: Sanity
Risks: None
Signed-off-by: SukanyaIlavarasi <sukanya.i@tataelxsi.co.in>

(cherry picked from commit fc7d4145782656ded097c59c9e8014172f2544ce)
Change-Id: I0222c8bbcddc41ca07dc532a0d79c835ce992416