RDKCOM-3534 RDKBCMF-300 Build errors in DhcpManager
Build errors in DhcpManager, this is blocking opensourcing of the component.
| source/DHCPServerUtils/dhcpv4_server_interface.c: In function 'dhcpv4_server_sysevent_handler':
| source/DHCPServerUtils/dhcpv4_server_interface.c:182:30: error: 'argv' undeclared (first use in this function)
|   182 |             else if(-- ( argv[1], dhcp_conf_change, 16))
|       |                          ^~~~
| source/DHCPServerUtils/dhcpv4_server_interface.c:182:30: note: each undeclared identifier is reported only once for each function it appears in
| source/DHCPServerUtils/service_dhcp_server.c:129:12: error: 'getValueFromDevicePropsFile' defined but not used [-Werror=unused-function]
|   129 | static int getValueFromDevicePropsFile(char *str, char **value)
|       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
| source/TR-181/middle_layer_src/cosa_dhcpv6_dml.c: In function 'dhcp6c_mapt_mape_GetParamStringValue':
| source/TR-181/middle_layer_src/cosa_dhcpv6_dml.c:3474:37: error: unused parameter 'pUlSize' [-Werror=unused-parameter]
|  3474 |         ULONG*                      pUlSize
|       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
| source/TR-181/board_sbapi/cosa_dhcpv6_apis.c: In function 'CosaDmlDhcpv6cGetEnabled':
| source/TR-181/board_sbapi/cosa_dhcpv6_apis.c:2820:12: error: 'dibblerEnabled' undeclared (first use in this function)
|  2820 |         if(dibblerEnabled)
|       |            ^~~~~~~~~~~~~~
| source/TR-181/board_sbapi/cosa_dhcpv6_apis.c:2820:12: note: each undeclared identifier is reported only once for each function it appears in
| source/TR-181/board_sbapi/service_dhcpv4_client.c: In function 'dhcp_parse_vendor_info':
| source/TR-181/board_sbapi/service_dhcpv4_client.c:143:17: warning: unused parameter 'ethWanMode' [-Wunused-parameter]
|   143 |     char       *ethWanMode
|       |     ~~~~~~~~~~~~^~~~~~~~~~
| source/TR-181/include/cosa_apis_util.h:30:20: error: 'RdkBus_GetParamValues' declared 'static' but never defined [-Werror=unused-function]
|    30 | static ANSC_STATUS RdkBus_GetParamValues( char *pComponent, char *pBus, char *pParamName, char *pReturnVal );
|       |                    ^~~~~~~~~~~~~~~~~~~~~
| In file included from source/TR-181/middle_layer_src/cosa_dhcpv6_dml.c:76:
| source/TR-181/include/cosa_apis_util.h:30:20: error: 'RdkBus_GetParamValues' declared 'static' but never defined [-Werror=unused-function]
|    30 | static ANSC_STATUS RdkBus_GetParamValues( char *pComponent, char *pBus, char *pParamName, char *pReturnVal );
|       |                    ^~~~~~~~~~~~~~~~~~~~~
source/DHCPServerUtils/include/util.h:59:49: error: format '%s' expects a matching 'char *' argument [-Werror=format=]
   59 |                               CcspTraceError  ((%s - format\n, __FUNCTION__, ##__VA_ARGS__))
      |                                                 ^~~~~~~
source/TR-181/board_sbapi/cosa_dhcpv6_apis.c:7615: error: undefined reference to 'Get_Device_Mode'
source/TR-181/board_sbapi/cosa_dhcpv6_apis.c:8184: error: undefined reference to 'Get_Device_Mode'
etc.

Reason for change: RDKBCMF-300 Build errors in DhcpManager
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen_barrett@comcast.com>

(cherry picked from commit 734578161da81011b545785ad6c67d297df74b23)
Change-Id: Ia9468a10309e770c28ed091463a3d413671894b5