RDKCOM-4246: REFPLTB-2697 : Latest rpi4 64bit build is failing in DhcpManage...
Reason for change : To fix the below errors,
../../../../../../../../../../rdkb/components/opensource/ccsp/DhcpManager/source/TR-181/board_sbapi/cosa_dhcpv6_apis.c:9199:51:
error: format '%d' expects argument of type 'int', but argument 7 has
type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|  9199 | CcspTraceWarning(("%s: g_dhcpv6s_refresh_count %ld, globalIP2
is %s, strlen is %d\n", __func__,
g_dhcpv6s_refresh_count,globalIP2,strlen(globalIP2)));
|       |
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                           |
|       |                       size_t {aka long unsigned int}
Test Procedure: bitbake ccsp-dhcp-mgr should be successful in 64bit
compilation
Risks: Low
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

Reason for change: REFPLTB-2697 : Latest rpi4 64bit build is failing in DhcpManage...
Priority: P1

(cherry picked from commit d477feccdd4a7019bd701534756c24c0f30a67ac)
Change-Id: Ibab321be72f8234e9315920a5e3583c464459a0c