RDKCOM-3685: RDKBCMF-308 Build errors in DhcpManager
Reason for change:
Build errors in DhcpManager as a result of DhcpManager/+/81313:
 | DhcpManager/source/DHCPServerUtils/DHCPv6Server/dhcpv6server_function.c:1057:44: error: 'g_recv_option_num' undeclared (first use in this function); did you mean 'g_recv_options'?
|  1057 |                 for ( Index4 = 0; Index4 < g_recv_option_num; Index4++ )
|       |                                            ^~~~~~~~~~~~~~~~~
|       |                                            g_recv_options
| DhcpManager/source/DHCPServerUtils/DHCPv6Server/dhcpv6server_function.c:1057:44: note: each undeclared identifier is reported only once for each function it appears in
| At top level:
| DhcpManager/source/DHCPServerUtils/DHCPv6Server/dhcpv6server_function.c:551:16: error: 'sysevent_token_global' defined but not used [-Werror=unused-variable]
|   551 | static token_t sysevent_token_global;
|       |                ^~~~~~~~~~~~~~~~~~~~~
| DhcpManager/source/DHCPServerUtils/DHCPv6Server/dhcpv6server_function.c:550:12: error: 'sysevent_fd_global' defined but not used [-Werror=unused-variable]
|   550 | static int sysevent_fd_global = 0;
|       |            ^~~~~~~~~~~~~~~~~~
| cc1: all warnings being treated as errors

and the renamed source file DHCPServerUtils/DHCPv6Server/dhcpv6_server_functions.c is no longer used.

Test Procedure: Sanity.
Risks: None.

Signed-off-by: Simon Chung <simon_chung@comcast.com>
Change-Id: I9ccbb857c058881700273243d685b9c2c9534598