REFPLTB-2449 : DHCP manager compilation issues in kirkstone
Reason for change :
rdkb/components/opensource/ccsp/DhcpManager/source/DHCPClientUtils/DHCPv4Client/service_dhcpv4_client.c:230:67: error: format '%x' expects argument of type 'unsigned int', but argument 5 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|   230 |             rc = sprintf_s(options + opt_len, (length - opt_len), "%02x", strlen(subopt_value));
|       |                                                                   ^~~~~~  ~~~~~~~~~~~~~~~~~~~~
|       |
changed the int format to %zu,due to strlen()
Test Procedure: 1.Verified that it is not affecting dunfell build.
                2.do_compile issues should not be observed in dhcp-manager
Risks: Low

Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>
Change-Id: Ie2210282f4a7903337dd21329608cb415b437834